# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BooleanClicker
                                 A QGIS plugin
 Use left and right click to create Points with a boolean field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-27
        copyright            : (C) 2026 by Intecrop ltd.
        email                : robin@intecrop.io
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BooleanClicker class from file BooleanClicker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BooleanClicker import BooleanClicker
    return BooleanClicker(iface)
