# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BooleanClickerDialog
                                 A QGIS plugin
 Use left and right click to create Points with a boolean field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Intecrop ltd.
        email                : robin@intecrop.io
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QVariant, QSettings
from qgis.core import QgsProject, QgsWkbTypes, QgsMapLayerType

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'BooleanClicker_dialog_base.ui'))


class BooleanClickerDialog(QtWidgets.QDialog, FORM_CLASS):
    SETTINGS_BASE = 'BooleanClicker'
    SETTINGS_LAYER_ID = '{}/last_layer_id'
    SETTINGS_FIELD_NAME = '{}/last_field_name'
    SETTINGS_CENTER_ON_CLICK = '{}/center_on_click'
    SETTINGS_RECENTER_X = '{}/recenter_x_percent'
    SETTINGS_RECENTER_Y = '{}/recenter_y_percent'

    def __init__(self, parent=None):
        """Constructor."""
        super(BooleanClickerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.layer_combo.currentIndexChanged.connect(self._populate_boolean_fields)
        self.center_on_click_checkbox.toggled.connect(self._update_recenter_controls_enabled)
        self.settings = QSettings()
        self._setup_recenter_options()
        self.center_on_click_checkbox.setChecked(
            self.settings.value(
                self.SETTINGS_CENTER_ON_CLICK.format(self.SETTINGS_BASE),
                False,
                type=bool
            )
        )
        saved_x = self.settings.value(
            self.SETTINGS_RECENTER_X.format(self.SETTINGS_BASE),
            50,
            type=int
        )
        saved_y = self.settings.value(
            self.SETTINGS_RECENTER_Y.format(self.SETTINGS_BASE),
            50,
            type=int
        )
        self._set_combo_to_value(self.horizontal_position_combo, saved_x)
        self._set_combo_to_value(self.vertical_position_combo, saved_y)
        self._update_recenter_controls_enabled(self.center_on_click_checkbox.isChecked())

    def _update_recenter_controls_enabled(self, enabled):
        self.horizontal_position_label.setEnabled(enabled)
        self.horizontal_position_combo.setEnabled(enabled)
        self.vertical_position_label.setEnabled(enabled)
        self.vertical_position_combo.setEnabled(enabled)

    def _setup_recenter_options(self):
        self.horizontal_position_combo.clear()
        self.vertical_position_combo.clear()

        self.horizontal_position_combo.addItem('0% (left)', 0)
        self.horizontal_position_combo.addItem('10%', 10)
        self.horizontal_position_combo.addItem('20%', 20)
        self.horizontal_position_combo.addItem('30%', 30)
        self.horizontal_position_combo.addItem('40%', 40)
        self.horizontal_position_combo.addItem('50% (center)', 50)
        self.horizontal_position_combo.addItem('60%', 60)
        self.horizontal_position_combo.addItem('70%', 70)
        self.horizontal_position_combo.addItem('80%', 80)
        self.horizontal_position_combo.addItem('90%', 90)
        self.horizontal_position_combo.addItem('100% (right)', 100)

        self.vertical_position_combo.addItem('0% (top)', 0)
        self.vertical_position_combo.addItem('10%', 10)
        self.vertical_position_combo.addItem('20%', 20)
        self.vertical_position_combo.addItem('30%', 30)
        self.vertical_position_combo.addItem('40%', 40)
        self.vertical_position_combo.addItem('50% (middle)', 50)
        self.vertical_position_combo.addItem('60%', 60)
        self.vertical_position_combo.addItem('70%', 70)
        self.vertical_position_combo.addItem('80%', 80)
        self.vertical_position_combo.addItem('90%', 90)
        self.vertical_position_combo.addItem('100% (bottom)', 100)

    def _set_combo_to_value(self, combo, value):
        index = combo.findData(value)
        if index < 0:
            index = combo.findData(50)
        if index >= 0:
            combo.setCurrentIndex(index)

    def refresh_choices(self):
        previous_layer_id = self.layer_combo.currentData()
        if not previous_layer_id:
            previous_layer_id = self.settings.value(
                self.SETTINGS_LAYER_ID.format(self.SETTINGS_BASE),
                '',
                type=str
            )
        elif previous_layer_id is not None:
            previous_layer_id = str(previous_layer_id)

        previous_field_name = self.field_combo.currentText()
        if not previous_field_name:
            previous_field_name = self.settings.value(
                self.SETTINGS_FIELD_NAME.format(self.SETTINGS_BASE),
                '',
                type=str
            )
        elif previous_field_name is not None:
            previous_field_name = str(previous_field_name)

        self.layer_combo.blockSignals(True)
        self.layer_combo.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() != QgsMapLayerType.VectorLayer:
                continue
            if layer.geometryType() != QgsWkbTypes.PointGeometry:
                continue
            if not any(field.type() == QVariant.Bool for field in layer.fields()):
                continue

            self.layer_combo.addItem(layer.name(), layer.id())

        self.layer_combo.blockSignals(False)

        if previous_layer_id:
            index = self.layer_combo.findData(previous_layer_id)
            if index >= 0:
                self.layer_combo.setCurrentIndex(index)

        self._populate_boolean_fields(previous_field_name)

    def _populate_boolean_fields(self, preferred_field_name=None):
        self.field_combo.clear()

        layer = self.selected_layer()
        if layer is None:
            return

        for field in layer.fields():
            if field.type() == QVariant.Bool:
                self.field_combo.addItem(field.name())

        if preferred_field_name is not None:
            preferred_field_name = str(preferred_field_name)

        if preferred_field_name:
            index = self.field_combo.findText(preferred_field_name)
            if index >= 0:
                self.field_combo.setCurrentIndex(index)

    def selected_layer(self):
        layer_id = self.layer_combo.currentData()
        if not layer_id:
            return None

        return QgsProject.instance().mapLayer(layer_id)

    def selected_field_name(self):
        return self.field_combo.currentText()

    def should_center_on_click(self):
        return self.center_on_click_checkbox.isChecked()

    def recenter_x_fraction(self):
        value = self.horizontal_position_combo.currentData()
        return (value if value is not None else 50) / 100.0

    def recenter_y_fraction(self):
        value = self.vertical_position_combo.currentData()
        return (value if value is not None else 50) / 100.0

    def accept(self):
        layer = self.selected_layer()
        self.settings.setValue(
            self.SETTINGS_LAYER_ID.format(self.SETTINGS_BASE),
            layer.id() if layer else ''
        )
        self.settings.setValue(
            self.SETTINGS_FIELD_NAME.format(self.SETTINGS_BASE),
            self.selected_field_name()
        )
        self.settings.setValue(
            self.SETTINGS_CENTER_ON_CLICK.format(self.SETTINGS_BASE),
            self.should_center_on_click()
        )
        self.settings.setValue(
            self.SETTINGS_RECENTER_X.format(self.SETTINGS_BASE),
            int(self.recenter_x_fraction() * 100)
        )
        self.settings.setValue(
            self.SETTINGS_RECENTER_Y.format(self.SETTINGS_BASE),
            int(self.recenter_y_fraction() * 100)
        )
        super(BooleanClickerDialog, self).accept()
