# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BooleanClicker
                                 A QGIS plugin
 Use left and right click to create Points with a boolean field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-27
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Intecrop ltd.
        email                : robin@intecrop.io
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsFeature, QgsGeometry, QgsRectangle
from qgis.gui import QgsMapTool, QgsVertexMarker

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .BooleanClicker_dialog import BooleanClickerDialog
import os.path


class BooleanPointMapTool(QgsMapTool):
    def __init__(
        self,
        iface,
        layer,
        field_name,
        center_on_click=False,
        recenter_x_fraction=0.5,
        recenter_y_fraction=0.5
    ):
        super().__init__(iface.mapCanvas())
        self.iface = iface
        self.layer = layer
        self.field_name = field_name
        self.center_on_click = center_on_click
        self.recenter_x_fraction = recenter_x_fraction
        self.recenter_y_fraction = recenter_y_fraction
        self.preview_marker = None
        self.last_mouse_pos = None
        self.extent_signal_connected = False

    def _snapped_map_point_from_pos(self, screen_pos):
        map_point = self.toMapCoordinates(screen_pos)
        snapping_utils = self.iface.mapCanvas().snappingUtils()
        if snapping_utils is not None:
            match = snapping_utils.snapToMap(screen_pos)
            if match.isValid():
                return match.point(), True
        return map_point, False

    def _refresh_preview_marker(self):
        if self.last_mouse_pos is None:
            return

        self._ensure_preview_marker()
        map_point, _ = self._snapped_map_point_from_pos(self.last_mouse_pos)
        self.preview_marker.setCenter(map_point)
        self.preview_marker.show()

    def _ensure_preview_marker(self):
        if self.preview_marker is None:
            self.preview_marker = QgsVertexMarker(self.iface.mapCanvas())
            self.preview_marker.setIconType(QgsVertexMarker.ICON_BOX)
            self.preview_marker.setColor(QColor(255, 80, 170))
            self.preview_marker.setIconSize(12)
            self.preview_marker.setPenWidth(2)
            self.preview_marker.hide()

    def canvasMoveEvent(self, event):
        self.last_mouse_pos = event.pos()
        self._refresh_preview_marker()

    def canvasReleaseEvent(self, event):
        if event.button() not in (Qt.LeftButton, Qt.RightButton):
            return

        if not self.layer or not self.layer.isValid():
            self.iface.messageBar().pushWarning(
                'BooleanClicker',
                'Selected layer is no longer available.'
            )
            return

        if self.field_name not in self.layer.fields().names():
            self.iface.messageBar().pushWarning(
                'BooleanClicker',
                'Selected boolean field is no longer available.'
            )
            return

        if not self.layer.isEditable() and not self.layer.startEditing():
            self.iface.messageBar().pushWarning(
                'BooleanClicker',
                'Could not start editing on the selected layer.'
            )
            return

        map_point, _ = self._snapped_map_point_from_pos(event.pos())

        point = self.toLayerCoordinates(self.layer, map_point)

        feature = QgsFeature(self.layer.fields())
        feature.setGeometry(QgsGeometry.fromPointXY(point))
        feature.setAttribute(self.field_name, event.button() == Qt.LeftButton)

        if not self.layer.addFeature(feature):
            self.iface.messageBar().pushWarning(
                'BooleanClicker',
                'Failed to add point feature to the layer.'
            )
            return

        self.layer.triggerRepaint()

        if self.center_on_click:
            canvas = self.iface.mapCanvas()
            extent = canvas.extent()
            width = extent.width()
            height = extent.height()

            new_center_x = map_point.x() + (0.5 - self.recenter_x_fraction) * width
            new_center_y = map_point.y() + (self.recenter_y_fraction - 0.5) * height

            new_extent = QgsRectangle(
                new_center_x - width / 2.0,
                new_center_y - height / 2.0,
                new_center_x + width / 2.0,
                new_center_y + height / 2.0
            )
            canvas.setExtent(new_extent)
            canvas.refresh()

    def deactivate(self):
        if self.extent_signal_connected:
            self.iface.mapCanvas().extentsChanged.disconnect(self._refresh_preview_marker)
            self.extent_signal_connected = False

        if self.preview_marker is not None:
            self.preview_marker.hide()
        super().deactivate()

    def activate(self):
        if not self.extent_signal_connected:
            self.iface.mapCanvas().extentsChanged.connect(self._refresh_preview_marker)
            self.extent_signal_connected = True
        super().activate()


class BooleanClicker:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'BooleanClicker_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&BooleanClicker')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.map_tool = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BooleanClicker', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/BooleanClicker/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Select point layer with Boolean field'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.map_tool and self.iface.mapCanvas().mapTool() == self.map_tool:
            self.iface.mapCanvas().unsetMapTool(self.map_tool)

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&BooleanClicker'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = BooleanClickerDialog()

        self.dlg.refresh_choices()

        if self.dlg.layer_combo.count() == 0:
            self.iface.messageBar().pushWarning(
                'BooleanClicker',
                'No point vector layers are available in the current project.'
            )
            return

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            layer = self.dlg.selected_layer()
            field_name = self.dlg.selected_field_name()
            center_on_click = self.dlg.should_center_on_click()
            recenter_x_fraction = self.dlg.recenter_x_fraction()
            recenter_y_fraction = self.dlg.recenter_y_fraction()

            if layer is None:
                self.iface.messageBar().pushWarning(
                    'BooleanClicker',
                    'Please select a point layer.'
                )
                return

            if not field_name:
                self.iface.messageBar().pushWarning(
                    'BooleanClicker',
                    'Please select a boolean field.'
                )
                return

            self.map_tool = BooleanPointMapTool(
                self.iface,
                layer,
                field_name,
                center_on_click=center_on_click,
                recenter_x_fraction=recenter_x_fraction,
                recenter_y_fraction=recenter_y_fraction
            )
            self.iface.mapCanvas().setMapTool(self.map_tool)
            self.iface.messageBar().pushMessage(
                'BooleanClicker',
                'Tool active: left click adds True, right click adds False.',
                level=0,
                duration=5
            )
